Initial cleanup
Yoast/cloudflare-tag-purge pull request #1
Opened 2022-02-23 14:19 UTC by jdevalk

2022-02-23 14:30 UTC, Djennez commented
Should this check for WordPress context to prevent error log contamination by calling the file directly without WP context?

2022-02-23 14:36 UTC, diedexx requested changes

2022-02-23 14:36 UTC, diedexx commented on cloudflare-tag-purge.php
> +		add_action( 'plugin_loaded', [ $this, 'register_hooks' ] );
```suggestion
		add_action( 'plugins_loaded', [ $this, 'register_hooks' ] );
```

2022-02-23 14:36 UTC, diedexx commented on cloudflare-tag-purge.php
> +	public function purge_action_edit_post( int $post_id, WP_Post $post ) {
```suggestion
	public function purge_action_edit_post($post_id, $post ) {
		if ( ! is_int( $post_id ) || ! is_a( $post, WP_Post::class ) ) {
			return;
		}
```

2022-02-23 14:36 UTC, diedexx commented on cloudflare-tag-purge.php
> +		$tags = [ $this->get_cache_prefix() . 'postid-' . (int) $post_id ];
No need to cast with the typed argument
```suggestion
		$tags = [ $this->get_cache_prefix() . 'postid-' . $post_id ];
```

2022-02-23 14:36 UTC, diedexx commented on cloudflare-tag-purge.php
> +			$this->cloudflare_cache_clear( [ 'files' => [ $sitemap_url ] ] );
I think we should always clear the sitemap index cache and also the sitemap of the specific object_types

2022-02-23 14:40 UTC, diedexx commented
I'd like to move this to the yoast.com repo. That way we have access to existing logging strategies which sync to ELK and the yoast.com/academy team can more easily maintain this.
It's already fairly specific to yoast.com

2026-05-24 19:24 UTC, jdevalk commented
Closing — opened Feb 2022, changes-requested never addressed, and I no longer work at Yoast.

2026-05-24 19:24 UTC, closed without merging